### ISSUE TITLE
Failed pip install 

### ISSUE THREAD

**Issue by eodole** [K-RLange/ttta#15]
Hi I tried installing this package with pip and it seems to fail and I'm not entirely sure why. I'm using MacOS with an M1 chip which sometimes causes problems. Anyway here is the error: 

error: subprocess-exited-with-error
  
 ```
 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/w1/xlpywrcj649gwbnsk6yt36w80000gn/T/pip-install-8s45x8gz/wordcloud_54a0895742864ec8acd1179f14a6f371/setup.py", line 13, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/w1/xlpywrcj649gwbnsk6yt36w80000gn/T/pip-install-8s45x8gz/wordcloud_54a0895742864ec8acd1179f14a6f371/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/w1/xlpywrcj649gwbnsk6yt36w80000gn/T/pip-install-8s45x8gz/wordcloud_54a0895742864ec8acd1179f14a6f371/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/w1/xlpywrcj649gwbnsk6yt36w80000gn/T/pip-install-8s45x8gz/wordcloud_54a0895742864ec8acd1179f14a6f371/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by K-RLange** [comment]
Hi!
This seems to be a problem with visoineer, apparenty caused while installing the wordcloud package that is a dependency of ttta. But maybe more information could help me narrow down the cause for this. Could you tell me what Python version you are using?

**Comment by eodole** [comment]
Hi! 

In my environment I used  Python 3.10.13. I used this package for a project and someone else suggested to use Python 3.9, so I tried installing ttta into a conda environment with  python=3.9.20 , numpy, pandas and scipy but encountered futher problems. 

Error 1: 
``` 
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      /bin/sh: pkg-config: command not found
      Failed to find sentencepiece pkgconfig
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``` 

I then tried installing pkg-config from conda forge. I ran `pip install ttta` again but encountered the following error 

``` 
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      Package sentencepiece was not found in the pkg-config search path.
      Perhaps you should add the directory containing `sentencepiece.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'sentencepiece' found
      Failed to find sentencepiece pkgconfig
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``` 

I know that this is probably user error, but please let me know what you think.

**Comment by K-RLange** [comment]
I have made some changes and fixed some bugs for the package. Could you try to install the latest pypi-version again and tell me if it still fails?

**Comment by eodole** [comment]
It works! Thank you!
